# Site settings
title: "@dulaccc"
email: "pierre@dulaccc.me"
description: "Hi everyone, I'm an iOS developer, I love Django to build my backend, and I love Backbone to build the front. Basically, I build iOS apps from start to finish. By the way, I love photography and has a Nuclear Civil Engineering degree in my pocket."
baseurl: ""
url: "http://dulaccc.me"

# User settings
author: Pierre Dulac
username: dulaccc

# Build settings
markdown: kramdown
permalink: /:year/:month/:title.html
highlighter: rouge
