# Site settings
title: "@dulacp"
email: "dulacpier@gmail.com"
description: "Hi everyone, I am a full-stack developer. I write mainly about iOS, Django, Heroku."
baseurl: ""
url: "https://dulacp.com"

# User settings
author: Pierre Dulac
username: dulacp

# Build settings
markdown: kramdown
permalink: /:year/:month/:title.html

highlighter: rouge
kramdown:
  syntax_highlighter: rouge
